/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../../../../common";

export type FundingCyclePropertiesStruct = {
  target: PromiseOrValue<BigNumberish>;
  currency: PromiseOrValue<BigNumberish>;
  duration: PromiseOrValue<BigNumberish>;
  cycleLimit: PromiseOrValue<BigNumberish>;
  discountRate: PromiseOrValue<BigNumberish>;
  ballot: PromiseOrValue<string>;
};

export type FundingCyclePropertiesStructOutput = [
  BigNumber,
  BigNumber,
  BigNumber,
  BigNumber,
  BigNumber,
  string
] & {
  target: BigNumber;
  currency: BigNumber;
  duration: BigNumber;
  cycleLimit: BigNumber;
  discountRate: BigNumber;
  ballot: string;
};

export type FundingCycleStruct = {
  id: PromiseOrValue<BigNumberish>;
  projectId: PromiseOrValue<BigNumberish>;
  number: PromiseOrValue<BigNumberish>;
  basedOn: PromiseOrValue<BigNumberish>;
  configured: PromiseOrValue<BigNumberish>;
  cycleLimit: PromiseOrValue<BigNumberish>;
  weight: PromiseOrValue<BigNumberish>;
  ballot: PromiseOrValue<string>;
  start: PromiseOrValue<BigNumberish>;
  duration: PromiseOrValue<BigNumberish>;
  target: PromiseOrValue<BigNumberish>;
  currency: PromiseOrValue<BigNumberish>;
  fee: PromiseOrValue<BigNumberish>;
  discountRate: PromiseOrValue<BigNumberish>;
  tapped: PromiseOrValue<BigNumberish>;
  metadata: PromiseOrValue<BigNumberish>;
};

export type FundingCycleStructOutput = [
  BigNumber,
  BigNumber,
  BigNumber,
  BigNumber,
  BigNumber,
  BigNumber,
  BigNumber,
  string,
  BigNumber,
  BigNumber,
  BigNumber,
  BigNumber,
  BigNumber,
  BigNumber,
  BigNumber,
  BigNumber
] & {
  id: BigNumber;
  projectId: BigNumber;
  number: BigNumber;
  basedOn: BigNumber;
  configured: BigNumber;
  cycleLimit: BigNumber;
  weight: BigNumber;
  ballot: string;
  start: BigNumber;
  duration: BigNumber;
  target: BigNumber;
  currency: BigNumber;
  fee: BigNumber;
  discountRate: BigNumber;
  tapped: BigNumber;
  metadata: BigNumber;
};

export interface IFundingCyclesInterface extends utils.Interface {
  functions: {
    "BASE_WEIGHT()": FunctionFragment;
    "MAX_CYCLE_LIMIT()": FunctionFragment;
    "configure(uint256,(uint256,uint256,uint256,uint256,uint256,address),uint256,uint256,bool)": FunctionFragment;
    "count()": FunctionFragment;
    "currentBallotStateOf(uint256)": FunctionFragment;
    "currentOf(uint256)": FunctionFragment;
    "get(uint256)": FunctionFragment;
    "latestIdOf(uint256)": FunctionFragment;
    "queuedOf(uint256)": FunctionFragment;
    "tap(uint256,uint256)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "BASE_WEIGHT"
      | "MAX_CYCLE_LIMIT"
      | "configure"
      | "count"
      | "currentBallotStateOf"
      | "currentOf"
      | "get"
      | "latestIdOf"
      | "queuedOf"
      | "tap"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "BASE_WEIGHT",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MAX_CYCLE_LIMIT",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "configure",
    values: [
      PromiseOrValue<BigNumberish>,
      FundingCyclePropertiesStruct,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<boolean>
    ]
  ): string;
  encodeFunctionData(functionFragment: "count", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "currentBallotStateOf",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "currentOf",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "get",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "latestIdOf",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "queuedOf",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "tap",
    values: [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>]
  ): string;

  decodeFunctionResult(
    functionFragment: "BASE_WEIGHT",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MAX_CYCLE_LIMIT",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "configure", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "count", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "currentBallotStateOf",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "currentOf", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "get", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "latestIdOf", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "queuedOf", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "tap", data: BytesLike): Result;

  events: {
    "Configure(uint256,uint256,uint256,tuple,uint256,address)": EventFragment;
    "Init(uint256,uint256,uint256,uint256,uint256,uint256)": EventFragment;
    "Tap(uint256,uint256,uint256,uint256,address)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "Configure"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Init"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Tap"): EventFragment;
}

export interface ConfigureEventObject {
  fundingCycleId: BigNumber;
  projectId: BigNumber;
  reconfigured: BigNumber;
  _properties: FundingCyclePropertiesStructOutput;
  metadata: BigNumber;
  caller: string;
}
export type ConfigureEvent = TypedEvent<
  [
    BigNumber,
    BigNumber,
    BigNumber,
    FundingCyclePropertiesStructOutput,
    BigNumber,
    string
  ],
  ConfigureEventObject
>;

export type ConfigureEventFilter = TypedEventFilter<ConfigureEvent>;

export interface InitEventObject {
  fundingCycleId: BigNumber;
  projectId: BigNumber;
  number: BigNumber;
  previous: BigNumber;
  weight: BigNumber;
  start: BigNumber;
}
export type InitEvent = TypedEvent<
  [BigNumber, BigNumber, BigNumber, BigNumber, BigNumber, BigNumber],
  InitEventObject
>;

export type InitEventFilter = TypedEventFilter<InitEvent>;

export interface TapEventObject {
  fundingCycleId: BigNumber;
  projectId: BigNumber;
  amount: BigNumber;
  newTappedAmount: BigNumber;
  caller: string;
}
export type TapEvent = TypedEvent<
  [BigNumber, BigNumber, BigNumber, BigNumber, string],
  TapEventObject
>;

export type TapEventFilter = TypedEventFilter<TapEvent>;

export interface IFundingCycles extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: IFundingCyclesInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    BASE_WEIGHT(overrides?: CallOverrides): Promise<[BigNumber]>;

    MAX_CYCLE_LIMIT(overrides?: CallOverrides): Promise<[BigNumber]>;

    configure(
      _projectId: PromiseOrValue<BigNumberish>,
      _properties: FundingCyclePropertiesStruct,
      _metadata: PromiseOrValue<BigNumberish>,
      _fee: PromiseOrValue<BigNumberish>,
      _configureActiveFundingCycle: PromiseOrValue<boolean>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    count(overrides?: CallOverrides): Promise<[BigNumber]>;

    currentBallotStateOf(
      _projectId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[number]>;

    currentOf(
      _projectId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[FundingCycleStructOutput]>;

    get(
      _fundingCycleId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[FundingCycleStructOutput]>;

    latestIdOf(
      _projectId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    queuedOf(
      _projectId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[FundingCycleStructOutput]>;

    tap(
      _projectId: PromiseOrValue<BigNumberish>,
      _amount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;
  };

  BASE_WEIGHT(overrides?: CallOverrides): Promise<BigNumber>;

  MAX_CYCLE_LIMIT(overrides?: CallOverrides): Promise<BigNumber>;

  configure(
    _projectId: PromiseOrValue<BigNumberish>,
    _properties: FundingCyclePropertiesStruct,
    _metadata: PromiseOrValue<BigNumberish>,
    _fee: PromiseOrValue<BigNumberish>,
    _configureActiveFundingCycle: PromiseOrValue<boolean>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  count(overrides?: CallOverrides): Promise<BigNumber>;

  currentBallotStateOf(
    _projectId: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<number>;

  currentOf(
    _projectId: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<FundingCycleStructOutput>;

  get(
    _fundingCycleId: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<FundingCycleStructOutput>;

  latestIdOf(
    _projectId: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  queuedOf(
    _projectId: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<FundingCycleStructOutput>;

  tap(
    _projectId: PromiseOrValue<BigNumberish>,
    _amount: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    BASE_WEIGHT(overrides?: CallOverrides): Promise<BigNumber>;

    MAX_CYCLE_LIMIT(overrides?: CallOverrides): Promise<BigNumber>;

    configure(
      _projectId: PromiseOrValue<BigNumberish>,
      _properties: FundingCyclePropertiesStruct,
      _metadata: PromiseOrValue<BigNumberish>,
      _fee: PromiseOrValue<BigNumberish>,
      _configureActiveFundingCycle: PromiseOrValue<boolean>,
      overrides?: CallOverrides
    ): Promise<FundingCycleStructOutput>;

    count(overrides?: CallOverrides): Promise<BigNumber>;

    currentBallotStateOf(
      _projectId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<number>;

    currentOf(
      _projectId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<FundingCycleStructOutput>;

    get(
      _fundingCycleId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<FundingCycleStructOutput>;

    latestIdOf(
      _projectId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    queuedOf(
      _projectId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<FundingCycleStructOutput>;

    tap(
      _projectId: PromiseOrValue<BigNumberish>,
      _amount: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<FundingCycleStructOutput>;
  };

  filters: {
    "Configure(uint256,uint256,uint256,tuple,uint256,address)"(
      fundingCycleId?: PromiseOrValue<BigNumberish> | null,
      projectId?: PromiseOrValue<BigNumberish> | null,
      reconfigured?: null,
      _properties?: null,
      metadata?: null,
      caller?: null
    ): ConfigureEventFilter;
    Configure(
      fundingCycleId?: PromiseOrValue<BigNumberish> | null,
      projectId?: PromiseOrValue<BigNumberish> | null,
      reconfigured?: null,
      _properties?: null,
      metadata?: null,
      caller?: null
    ): ConfigureEventFilter;

    "Init(uint256,uint256,uint256,uint256,uint256,uint256)"(
      fundingCycleId?: PromiseOrValue<BigNumberish> | null,
      projectId?: PromiseOrValue<BigNumberish> | null,
      number?: null,
      previous?: null,
      weight?: null,
      start?: null
    ): InitEventFilter;
    Init(
      fundingCycleId?: PromiseOrValue<BigNumberish> | null,
      projectId?: PromiseOrValue<BigNumberish> | null,
      number?: null,
      previous?: null,
      weight?: null,
      start?: null
    ): InitEventFilter;

    "Tap(uint256,uint256,uint256,uint256,address)"(
      fundingCycleId?: PromiseOrValue<BigNumberish> | null,
      projectId?: PromiseOrValue<BigNumberish> | null,
      amount?: null,
      newTappedAmount?: null,
      caller?: null
    ): TapEventFilter;
    Tap(
      fundingCycleId?: PromiseOrValue<BigNumberish> | null,
      projectId?: PromiseOrValue<BigNumberish> | null,
      amount?: null,
      newTappedAmount?: null,
      caller?: null
    ): TapEventFilter;
  };

  estimateGas: {
    BASE_WEIGHT(overrides?: CallOverrides): Promise<BigNumber>;

    MAX_CYCLE_LIMIT(overrides?: CallOverrides): Promise<BigNumber>;

    configure(
      _projectId: PromiseOrValue<BigNumberish>,
      _properties: FundingCyclePropertiesStruct,
      _metadata: PromiseOrValue<BigNumberish>,
      _fee: PromiseOrValue<BigNumberish>,
      _configureActiveFundingCycle: PromiseOrValue<boolean>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    count(overrides?: CallOverrides): Promise<BigNumber>;

    currentBallotStateOf(
      _projectId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    currentOf(
      _projectId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    get(
      _fundingCycleId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    latestIdOf(
      _projectId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    queuedOf(
      _projectId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    tap(
      _projectId: PromiseOrValue<BigNumberish>,
      _amount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    BASE_WEIGHT(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    MAX_CYCLE_LIMIT(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    configure(
      _projectId: PromiseOrValue<BigNumberish>,
      _properties: FundingCyclePropertiesStruct,
      _metadata: PromiseOrValue<BigNumberish>,
      _fee: PromiseOrValue<BigNumberish>,
      _configureActiveFundingCycle: PromiseOrValue<boolean>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    count(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    currentBallotStateOf(
      _projectId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    currentOf(
      _projectId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    get(
      _fundingCycleId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    latestIdOf(
      _projectId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    queuedOf(
      _projectId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    tap(
      _projectId: PromiseOrValue<BigNumberish>,
      _amount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;
  };
}
