/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PayableOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../../../common";

export type PayoutModStruct = {
  preferUnstaked: PromiseOrValue<boolean>;
  percent: PromiseOrValue<BigNumberish>;
  lockedUntil: PromiseOrValue<BigNumberish>;
  beneficiary: PromiseOrValue<string>;
  allocator: PromiseOrValue<string>;
  projectId: PromiseOrValue<BigNumberish>;
};

export type PayoutModStructOutput = [
  boolean,
  number,
  number,
  string,
  string,
  BigNumber
] & {
  preferUnstaked: boolean;
  percent: number;
  lockedUntil: number;
  beneficiary: string;
  allocator: string;
  projectId: BigNumber;
};

export type TicketModStruct = {
  preferUnstaked: PromiseOrValue<boolean>;
  percent: PromiseOrValue<BigNumberish>;
  lockedUntil: PromiseOrValue<BigNumberish>;
  beneficiary: PromiseOrValue<string>;
};

export type TicketModStructOutput = [boolean, number, number, string] & {
  preferUnstaked: boolean;
  percent: number;
  lockedUntil: number;
  beneficiary: string;
};

export type FundingCyclePropertiesStruct = {
  target: PromiseOrValue<BigNumberish>;
  currency: PromiseOrValue<BigNumberish>;
  duration: PromiseOrValue<BigNumberish>;
  cycleLimit: PromiseOrValue<BigNumberish>;
  discountRate: PromiseOrValue<BigNumberish>;
  ballot: PromiseOrValue<string>;
};

export type FundingCyclePropertiesStructOutput = [
  BigNumber,
  BigNumber,
  BigNumber,
  BigNumber,
  BigNumber,
  string
] & {
  target: BigNumber;
  currency: BigNumber;
  duration: BigNumber;
  cycleLimit: BigNumber;
  discountRate: BigNumber;
  ballot: string;
};

export type FundingCycleMetadataStruct = {
  reservedRate: PromiseOrValue<BigNumberish>;
  bondingCurveRate: PromiseOrValue<BigNumberish>;
  reconfigurationBondingCurveRate: PromiseOrValue<BigNumberish>;
};

export type FundingCycleMetadataStructOutput = [
  BigNumber,
  BigNumber,
  BigNumber
] & {
  reservedRate: BigNumber;
  bondingCurveRate: BigNumber;
  reconfigurationBondingCurveRate: BigNumber;
};

export interface TerminalV1Interface extends utils.Interface {
  functions: {
    "acceptGovernance()": FunctionFragment;
    "addToBalance(uint256)": FunctionFragment;
    "allowMigration(address)": FunctionFragment;
    "appointGovernance(address)": FunctionFragment;
    "balanceOf(uint256)": FunctionFragment;
    "canPrintPreminedTickets(uint256)": FunctionFragment;
    "claimableOverflowOf(address,uint256,uint256)": FunctionFragment;
    "configure(uint256,(uint256,uint256,uint256,uint256,uint256,address),(uint256,uint256,uint256),(bool,uint16,uint48,address,address,uint56)[],(bool,uint16,uint48,address)[])": FunctionFragment;
    "currentOverflowOf(uint256)": FunctionFragment;
    "deploy(address,bytes32,string,(uint256,uint256,uint256,uint256,uint256,address),(uint256,uint256,uint256),(bool,uint16,uint48,address,address,uint56)[],(bool,uint16,uint48,address)[])": FunctionFragment;
    "fee()": FunctionFragment;
    "fundingCycles()": FunctionFragment;
    "governance()": FunctionFragment;
    "migrate(uint256,address)": FunctionFragment;
    "migrationIsAllowed(address)": FunctionFragment;
    "modStore()": FunctionFragment;
    "operatorStore()": FunctionFragment;
    "pay(uint256,address,string,bool)": FunctionFragment;
    "pendingGovernance()": FunctionFragment;
    "prices()": FunctionFragment;
    "printPreminedTickets(uint256,uint256,uint256,address,string,bool)": FunctionFragment;
    "printReservedTickets(uint256)": FunctionFragment;
    "projects()": FunctionFragment;
    "redeem(address,uint256,uint256,uint256,address,bool)": FunctionFragment;
    "reservedTicketBalanceOf(uint256,uint256)": FunctionFragment;
    "setFee(uint256)": FunctionFragment;
    "tap(uint256,uint256,uint256,uint256)": FunctionFragment;
    "terminalDirectory()": FunctionFragment;
    "ticketBooth()": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "acceptGovernance"
      | "addToBalance"
      | "allowMigration"
      | "appointGovernance"
      | "balanceOf"
      | "canPrintPreminedTickets"
      | "claimableOverflowOf"
      | "configure"
      | "currentOverflowOf"
      | "deploy"
      | "fee"
      | "fundingCycles"
      | "governance"
      | "migrate"
      | "migrationIsAllowed"
      | "modStore"
      | "operatorStore"
      | "pay"
      | "pendingGovernance"
      | "prices"
      | "printPreminedTickets"
      | "printReservedTickets"
      | "projects"
      | "redeem"
      | "reservedTicketBalanceOf"
      | "setFee"
      | "tap"
      | "terminalDirectory"
      | "ticketBooth"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "acceptGovernance",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "addToBalance",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "allowMigration",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "appointGovernance",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "balanceOf",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "canPrintPreminedTickets",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "claimableOverflowOf",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "configure",
    values: [
      PromiseOrValue<BigNumberish>,
      FundingCyclePropertiesStruct,
      FundingCycleMetadataStruct,
      PayoutModStruct[],
      TicketModStruct[]
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "currentOverflowOf",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "deploy",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<BytesLike>,
      PromiseOrValue<string>,
      FundingCyclePropertiesStruct,
      FundingCycleMetadataStruct,
      PayoutModStruct[],
      TicketModStruct[]
    ]
  ): string;
  encodeFunctionData(functionFragment: "fee", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "fundingCycles",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "governance",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "migrate",
    values: [PromiseOrValue<BigNumberish>, PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "migrationIsAllowed",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(functionFragment: "modStore", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "operatorStore",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "pay",
    values: [
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<boolean>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "pendingGovernance",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "prices", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "printPreminedTickets",
    values: [
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<boolean>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "printReservedTickets",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(functionFragment: "projects", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "redeem",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<string>,
      PromiseOrValue<boolean>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "reservedTicketBalanceOf",
    values: [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "setFee",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "tap",
    values: [
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "terminalDirectory",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "ticketBooth",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "acceptGovernance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "addToBalance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "allowMigration",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "appointGovernance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "balanceOf", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "canPrintPreminedTickets",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "claimableOverflowOf",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "configure", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "currentOverflowOf",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "deploy", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "fee", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "fundingCycles",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "governance", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "migrate", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "migrationIsAllowed",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "modStore", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "operatorStore",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "pay", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "pendingGovernance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "prices", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "printPreminedTickets",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "printReservedTickets",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "projects", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "redeem", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "reservedTicketBalanceOf",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setFee", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "tap", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "terminalDirectory",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "ticketBooth",
    data: BytesLike
  ): Result;

  events: {
    "AcceptGovernance(address)": EventFragment;
    "AddToBalance(uint256,uint256,address)": EventFragment;
    "AllowMigration(address)": EventFragment;
    "AppointGovernance(address)": EventFragment;
    "Configure(uint256,uint256,address)": EventFragment;
    "Deposit(uint256)": EventFragment;
    "DistributeToPayoutMod(uint256,uint256,tuple,uint256,address)": EventFragment;
    "DistributeToTicketMod(uint256,uint256,tuple,uint256,address)": EventFragment;
    "EnsureTargetLocalWei(uint256)": EventFragment;
    "Migrate(uint256,address,uint256,address)": EventFragment;
    "Pay(uint256,uint256,address,uint256,string,address)": EventFragment;
    "PrintPreminedTickets(uint256,address,uint256,uint256,string,address)": EventFragment;
    "PrintReserveTickets(uint256,uint256,address,uint256,uint256,address)": EventFragment;
    "Redeem(address,address,uint256,uint256,uint256,address)": EventFragment;
    "SetFee(uint256)": EventFragment;
    "SetTargetLocalWei(uint256)": EventFragment;
    "SetYielder(address)": EventFragment;
    "Tap(uint256,uint256,address,uint256,uint256,uint256,uint256,uint256,address)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "AcceptGovernance"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "AddToBalance"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "AllowMigration"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "AppointGovernance"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Configure"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Deposit"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "DistributeToPayoutMod"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "DistributeToTicketMod"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "EnsureTargetLocalWei"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Migrate"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Pay"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "PrintPreminedTickets"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "PrintReserveTickets"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Redeem"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "SetFee"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "SetTargetLocalWei"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "SetYielder"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Tap"): EventFragment;
}

export interface AcceptGovernanceEventObject {
  governance: string;
}
export type AcceptGovernanceEvent = TypedEvent<
  [string],
  AcceptGovernanceEventObject
>;

export type AcceptGovernanceEventFilter =
  TypedEventFilter<AcceptGovernanceEvent>;

export interface AddToBalanceEventObject {
  projectId: BigNumber;
  value: BigNumber;
  caller: string;
}
export type AddToBalanceEvent = TypedEvent<
  [BigNumber, BigNumber, string],
  AddToBalanceEventObject
>;

export type AddToBalanceEventFilter = TypedEventFilter<AddToBalanceEvent>;

export interface AllowMigrationEventObject {
  allowed: string;
}
export type AllowMigrationEvent = TypedEvent<
  [string],
  AllowMigrationEventObject
>;

export type AllowMigrationEventFilter = TypedEventFilter<AllowMigrationEvent>;

export interface AppointGovernanceEventObject {
  governance: string;
}
export type AppointGovernanceEvent = TypedEvent<
  [string],
  AppointGovernanceEventObject
>;

export type AppointGovernanceEventFilter =
  TypedEventFilter<AppointGovernanceEvent>;

export interface ConfigureEventObject {
  fundingCycleId: BigNumber;
  projectId: BigNumber;
  caller: string;
}
export type ConfigureEvent = TypedEvent<
  [BigNumber, BigNumber, string],
  ConfigureEventObject
>;

export type ConfigureEventFilter = TypedEventFilter<ConfigureEvent>;

export interface DepositEventObject {
  amount: BigNumber;
}
export type DepositEvent = TypedEvent<[BigNumber], DepositEventObject>;

export type DepositEventFilter = TypedEventFilter<DepositEvent>;

export interface DistributeToPayoutModEventObject {
  fundingCycleId: BigNumber;
  projectId: BigNumber;
  mod: PayoutModStructOutput;
  modCut: BigNumber;
  caller: string;
}
export type DistributeToPayoutModEvent = TypedEvent<
  [BigNumber, BigNumber, PayoutModStructOutput, BigNumber, string],
  DistributeToPayoutModEventObject
>;

export type DistributeToPayoutModEventFilter =
  TypedEventFilter<DistributeToPayoutModEvent>;

export interface DistributeToTicketModEventObject {
  fundingCycleId: BigNumber;
  projectId: BigNumber;
  mod: TicketModStructOutput;
  modCut: BigNumber;
  caller: string;
}
export type DistributeToTicketModEvent = TypedEvent<
  [BigNumber, BigNumber, TicketModStructOutput, BigNumber, string],
  DistributeToTicketModEventObject
>;

export type DistributeToTicketModEventFilter =
  TypedEventFilter<DistributeToTicketModEvent>;

export interface EnsureTargetLocalWeiEventObject {
  target: BigNumber;
}
export type EnsureTargetLocalWeiEvent = TypedEvent<
  [BigNumber],
  EnsureTargetLocalWeiEventObject
>;

export type EnsureTargetLocalWeiEventFilter =
  TypedEventFilter<EnsureTargetLocalWeiEvent>;

export interface MigrateEventObject {
  projectId: BigNumber;
  to: string;
  _amount: BigNumber;
  caller: string;
}
export type MigrateEvent = TypedEvent<
  [BigNumber, string, BigNumber, string],
  MigrateEventObject
>;

export type MigrateEventFilter = TypedEventFilter<MigrateEvent>;

export interface PayEventObject {
  fundingCycleId: BigNumber;
  projectId: BigNumber;
  beneficiary: string;
  amount: BigNumber;
  note: string;
  caller: string;
}
export type PayEvent = TypedEvent<
  [BigNumber, BigNumber, string, BigNumber, string, string],
  PayEventObject
>;

export type PayEventFilter = TypedEventFilter<PayEvent>;

export interface PrintPreminedTicketsEventObject {
  projectId: BigNumber;
  beneficiary: string;
  amount: BigNumber;
  currency: BigNumber;
  memo: string;
  caller: string;
}
export type PrintPreminedTicketsEvent = TypedEvent<
  [BigNumber, string, BigNumber, BigNumber, string, string],
  PrintPreminedTicketsEventObject
>;

export type PrintPreminedTicketsEventFilter =
  TypedEventFilter<PrintPreminedTicketsEvent>;

export interface PrintReserveTicketsEventObject {
  fundingCycleId: BigNumber;
  projectId: BigNumber;
  beneficiary: string;
  count: BigNumber;
  beneficiaryTicketAmount: BigNumber;
  caller: string;
}
export type PrintReserveTicketsEvent = TypedEvent<
  [BigNumber, BigNumber, string, BigNumber, BigNumber, string],
  PrintReserveTicketsEventObject
>;

export type PrintReserveTicketsEventFilter =
  TypedEventFilter<PrintReserveTicketsEvent>;

export interface RedeemEventObject {
  holder: string;
  beneficiary: string;
  _projectId: BigNumber;
  amount: BigNumber;
  returnAmount: BigNumber;
  caller: string;
}
export type RedeemEvent = TypedEvent<
  [string, string, BigNumber, BigNumber, BigNumber, string],
  RedeemEventObject
>;

export type RedeemEventFilter = TypedEventFilter<RedeemEvent>;

export interface SetFeeEventObject {
  _amount: BigNumber;
}
export type SetFeeEvent = TypedEvent<[BigNumber], SetFeeEventObject>;

export type SetFeeEventFilter = TypedEventFilter<SetFeeEvent>;

export interface SetTargetLocalWeiEventObject {
  amount: BigNumber;
}
export type SetTargetLocalWeiEvent = TypedEvent<
  [BigNumber],
  SetTargetLocalWeiEventObject
>;

export type SetTargetLocalWeiEventFilter =
  TypedEventFilter<SetTargetLocalWeiEvent>;

export interface SetYielderEventObject {
  newYielder: string;
}
export type SetYielderEvent = TypedEvent<[string], SetYielderEventObject>;

export type SetYielderEventFilter = TypedEventFilter<SetYielderEvent>;

export interface TapEventObject {
  fundingCycleId: BigNumber;
  projectId: BigNumber;
  beneficiary: string;
  amount: BigNumber;
  currency: BigNumber;
  netTransferAmount: BigNumber;
  beneficiaryTransferAmount: BigNumber;
  govFeeAmount: BigNumber;
  caller: string;
}
export type TapEvent = TypedEvent<
  [
    BigNumber,
    BigNumber,
    string,
    BigNumber,
    BigNumber,
    BigNumber,
    BigNumber,
    BigNumber,
    string
  ],
  TapEventObject
>;

export type TapEventFilter = TypedEventFilter<TapEvent>;

export interface TerminalV1 extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: TerminalV1Interface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    acceptGovernance(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    addToBalance(
      _projectId: PromiseOrValue<BigNumberish>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    allowMigration(
      _contract: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    appointGovernance(
      _pendingGovernance: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    balanceOf(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    canPrintPreminedTickets(
      _projectId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    claimableOverflowOf(
      _account: PromiseOrValue<string>,
      _projectId: PromiseOrValue<BigNumberish>,
      _count: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    configure(
      _projectId: PromiseOrValue<BigNumberish>,
      _properties: FundingCyclePropertiesStruct,
      _metadata: FundingCycleMetadataStruct,
      _payoutMods: PayoutModStruct[],
      _ticketMods: TicketModStruct[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    currentOverflowOf(
      _projectId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[BigNumber] & { overflow: BigNumber }>;

    deploy(
      _owner: PromiseOrValue<string>,
      _handle: PromiseOrValue<BytesLike>,
      _uri: PromiseOrValue<string>,
      _properties: FundingCyclePropertiesStruct,
      _metadata: FundingCycleMetadataStruct,
      _payoutMods: PayoutModStruct[],
      _ticketMods: TicketModStruct[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    fee(overrides?: CallOverrides): Promise<[BigNumber]>;

    fundingCycles(overrides?: CallOverrides): Promise<[string]>;

    governance(overrides?: CallOverrides): Promise<[string]>;

    migrate(
      _projectId: PromiseOrValue<BigNumberish>,
      _to: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    migrationIsAllowed(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    modStore(overrides?: CallOverrides): Promise<[string]>;

    operatorStore(overrides?: CallOverrides): Promise<[string]>;

    pay(
      _projectId: PromiseOrValue<BigNumberish>,
      _beneficiary: PromiseOrValue<string>,
      _memo: PromiseOrValue<string>,
      _preferUnstakedTickets: PromiseOrValue<boolean>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    pendingGovernance(overrides?: CallOverrides): Promise<[string]>;

    prices(overrides?: CallOverrides): Promise<[string]>;

    printPreminedTickets(
      _projectId: PromiseOrValue<BigNumberish>,
      _amount: PromiseOrValue<BigNumberish>,
      _currency: PromiseOrValue<BigNumberish>,
      _beneficiary: PromiseOrValue<string>,
      _memo: PromiseOrValue<string>,
      _preferUnstakedTickets: PromiseOrValue<boolean>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    printReservedTickets(
      _projectId: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    projects(overrides?: CallOverrides): Promise<[string]>;

    redeem(
      _account: PromiseOrValue<string>,
      _projectId: PromiseOrValue<BigNumberish>,
      _count: PromiseOrValue<BigNumberish>,
      _minReturnedWei: PromiseOrValue<BigNumberish>,
      _beneficiary: PromiseOrValue<string>,
      _preferUnstaked: PromiseOrValue<boolean>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    reservedTicketBalanceOf(
      _projectId: PromiseOrValue<BigNumberish>,
      _reservedRate: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    setFee(
      _fee: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    tap(
      _projectId: PromiseOrValue<BigNumberish>,
      _amount: PromiseOrValue<BigNumberish>,
      _currency: PromiseOrValue<BigNumberish>,
      _minReturnedWei: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    terminalDirectory(overrides?: CallOverrides): Promise<[string]>;

    ticketBooth(overrides?: CallOverrides): Promise<[string]>;
  };

  acceptGovernance(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  addToBalance(
    _projectId: PromiseOrValue<BigNumberish>,
    overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  allowMigration(
    _contract: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  appointGovernance(
    _pendingGovernance: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  balanceOf(
    arg0: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  canPrintPreminedTickets(
    _projectId: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<boolean>;

  claimableOverflowOf(
    _account: PromiseOrValue<string>,
    _projectId: PromiseOrValue<BigNumberish>,
    _count: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  configure(
    _projectId: PromiseOrValue<BigNumberish>,
    _properties: FundingCyclePropertiesStruct,
    _metadata: FundingCycleMetadataStruct,
    _payoutMods: PayoutModStruct[],
    _ticketMods: TicketModStruct[],
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  currentOverflowOf(
    _projectId: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  deploy(
    _owner: PromiseOrValue<string>,
    _handle: PromiseOrValue<BytesLike>,
    _uri: PromiseOrValue<string>,
    _properties: FundingCyclePropertiesStruct,
    _metadata: FundingCycleMetadataStruct,
    _payoutMods: PayoutModStruct[],
    _ticketMods: TicketModStruct[],
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  fee(overrides?: CallOverrides): Promise<BigNumber>;

  fundingCycles(overrides?: CallOverrides): Promise<string>;

  governance(overrides?: CallOverrides): Promise<string>;

  migrate(
    _projectId: PromiseOrValue<BigNumberish>,
    _to: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  migrationIsAllowed(
    arg0: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<boolean>;

  modStore(overrides?: CallOverrides): Promise<string>;

  operatorStore(overrides?: CallOverrides): Promise<string>;

  pay(
    _projectId: PromiseOrValue<BigNumberish>,
    _beneficiary: PromiseOrValue<string>,
    _memo: PromiseOrValue<string>,
    _preferUnstakedTickets: PromiseOrValue<boolean>,
    overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  pendingGovernance(overrides?: CallOverrides): Promise<string>;

  prices(overrides?: CallOverrides): Promise<string>;

  printPreminedTickets(
    _projectId: PromiseOrValue<BigNumberish>,
    _amount: PromiseOrValue<BigNumberish>,
    _currency: PromiseOrValue<BigNumberish>,
    _beneficiary: PromiseOrValue<string>,
    _memo: PromiseOrValue<string>,
    _preferUnstakedTickets: PromiseOrValue<boolean>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  printReservedTickets(
    _projectId: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  projects(overrides?: CallOverrides): Promise<string>;

  redeem(
    _account: PromiseOrValue<string>,
    _projectId: PromiseOrValue<BigNumberish>,
    _count: PromiseOrValue<BigNumberish>,
    _minReturnedWei: PromiseOrValue<BigNumberish>,
    _beneficiary: PromiseOrValue<string>,
    _preferUnstaked: PromiseOrValue<boolean>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  reservedTicketBalanceOf(
    _projectId: PromiseOrValue<BigNumberish>,
    _reservedRate: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  setFee(
    _fee: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  tap(
    _projectId: PromiseOrValue<BigNumberish>,
    _amount: PromiseOrValue<BigNumberish>,
    _currency: PromiseOrValue<BigNumberish>,
    _minReturnedWei: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  terminalDirectory(overrides?: CallOverrides): Promise<string>;

  ticketBooth(overrides?: CallOverrides): Promise<string>;

  callStatic: {
    acceptGovernance(overrides?: CallOverrides): Promise<void>;

    addToBalance(
      _projectId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    allowMigration(
      _contract: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    appointGovernance(
      _pendingGovernance: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    balanceOf(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    canPrintPreminedTickets(
      _projectId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<boolean>;

    claimableOverflowOf(
      _account: PromiseOrValue<string>,
      _projectId: PromiseOrValue<BigNumberish>,
      _count: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    configure(
      _projectId: PromiseOrValue<BigNumberish>,
      _properties: FundingCyclePropertiesStruct,
      _metadata: FundingCycleMetadataStruct,
      _payoutMods: PayoutModStruct[],
      _ticketMods: TicketModStruct[],
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    currentOverflowOf(
      _projectId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    deploy(
      _owner: PromiseOrValue<string>,
      _handle: PromiseOrValue<BytesLike>,
      _uri: PromiseOrValue<string>,
      _properties: FundingCyclePropertiesStruct,
      _metadata: FundingCycleMetadataStruct,
      _payoutMods: PayoutModStruct[],
      _ticketMods: TicketModStruct[],
      overrides?: CallOverrides
    ): Promise<void>;

    fee(overrides?: CallOverrides): Promise<BigNumber>;

    fundingCycles(overrides?: CallOverrides): Promise<string>;

    governance(overrides?: CallOverrides): Promise<string>;

    migrate(
      _projectId: PromiseOrValue<BigNumberish>,
      _to: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    migrationIsAllowed(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<boolean>;

    modStore(overrides?: CallOverrides): Promise<string>;

    operatorStore(overrides?: CallOverrides): Promise<string>;

    pay(
      _projectId: PromiseOrValue<BigNumberish>,
      _beneficiary: PromiseOrValue<string>,
      _memo: PromiseOrValue<string>,
      _preferUnstakedTickets: PromiseOrValue<boolean>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    pendingGovernance(overrides?: CallOverrides): Promise<string>;

    prices(overrides?: CallOverrides): Promise<string>;

    printPreminedTickets(
      _projectId: PromiseOrValue<BigNumberish>,
      _amount: PromiseOrValue<BigNumberish>,
      _currency: PromiseOrValue<BigNumberish>,
      _beneficiary: PromiseOrValue<string>,
      _memo: PromiseOrValue<string>,
      _preferUnstakedTickets: PromiseOrValue<boolean>,
      overrides?: CallOverrides
    ): Promise<void>;

    printReservedTickets(
      _projectId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    projects(overrides?: CallOverrides): Promise<string>;

    redeem(
      _account: PromiseOrValue<string>,
      _projectId: PromiseOrValue<BigNumberish>,
      _count: PromiseOrValue<BigNumberish>,
      _minReturnedWei: PromiseOrValue<BigNumberish>,
      _beneficiary: PromiseOrValue<string>,
      _preferUnstaked: PromiseOrValue<boolean>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    reservedTicketBalanceOf(
      _projectId: PromiseOrValue<BigNumberish>,
      _reservedRate: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    setFee(
      _fee: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    tap(
      _projectId: PromiseOrValue<BigNumberish>,
      _amount: PromiseOrValue<BigNumberish>,
      _currency: PromiseOrValue<BigNumberish>,
      _minReturnedWei: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    terminalDirectory(overrides?: CallOverrides): Promise<string>;

    ticketBooth(overrides?: CallOverrides): Promise<string>;
  };

  filters: {
    "AcceptGovernance(address)"(governance?: null): AcceptGovernanceEventFilter;
    AcceptGovernance(governance?: null): AcceptGovernanceEventFilter;

    "AddToBalance(uint256,uint256,address)"(
      projectId?: PromiseOrValue<BigNumberish> | null,
      value?: null,
      caller?: null
    ): AddToBalanceEventFilter;
    AddToBalance(
      projectId?: PromiseOrValue<BigNumberish> | null,
      value?: null,
      caller?: null
    ): AddToBalanceEventFilter;

    "AllowMigration(address)"(allowed?: null): AllowMigrationEventFilter;
    AllowMigration(allowed?: null): AllowMigrationEventFilter;

    "AppointGovernance(address)"(
      governance?: null
    ): AppointGovernanceEventFilter;
    AppointGovernance(governance?: null): AppointGovernanceEventFilter;

    "Configure(uint256,uint256,address)"(
      fundingCycleId?: PromiseOrValue<BigNumberish> | null,
      projectId?: PromiseOrValue<BigNumberish> | null,
      caller?: null
    ): ConfigureEventFilter;
    Configure(
      fundingCycleId?: PromiseOrValue<BigNumberish> | null,
      projectId?: PromiseOrValue<BigNumberish> | null,
      caller?: null
    ): ConfigureEventFilter;

    "Deposit(uint256)"(amount?: null): DepositEventFilter;
    Deposit(amount?: null): DepositEventFilter;

    "DistributeToPayoutMod(uint256,uint256,tuple,uint256,address)"(
      fundingCycleId?: PromiseOrValue<BigNumberish> | null,
      projectId?: PromiseOrValue<BigNumberish> | null,
      mod?: null,
      modCut?: null,
      caller?: null
    ): DistributeToPayoutModEventFilter;
    DistributeToPayoutMod(
      fundingCycleId?: PromiseOrValue<BigNumberish> | null,
      projectId?: PromiseOrValue<BigNumberish> | null,
      mod?: null,
      modCut?: null,
      caller?: null
    ): DistributeToPayoutModEventFilter;

    "DistributeToTicketMod(uint256,uint256,tuple,uint256,address)"(
      fundingCycleId?: PromiseOrValue<BigNumberish> | null,
      projectId?: PromiseOrValue<BigNumberish> | null,
      mod?: null,
      modCut?: null,
      caller?: null
    ): DistributeToTicketModEventFilter;
    DistributeToTicketMod(
      fundingCycleId?: PromiseOrValue<BigNumberish> | null,
      projectId?: PromiseOrValue<BigNumberish> | null,
      mod?: null,
      modCut?: null,
      caller?: null
    ): DistributeToTicketModEventFilter;

    "EnsureTargetLocalWei(uint256)"(
      target?: null
    ): EnsureTargetLocalWeiEventFilter;
    EnsureTargetLocalWei(target?: null): EnsureTargetLocalWeiEventFilter;

    "Migrate(uint256,address,uint256,address)"(
      projectId?: PromiseOrValue<BigNumberish> | null,
      to?: PromiseOrValue<string> | null,
      _amount?: null,
      caller?: null
    ): MigrateEventFilter;
    Migrate(
      projectId?: PromiseOrValue<BigNumberish> | null,
      to?: PromiseOrValue<string> | null,
      _amount?: null,
      caller?: null
    ): MigrateEventFilter;

    "Pay(uint256,uint256,address,uint256,string,address)"(
      fundingCycleId?: PromiseOrValue<BigNumberish> | null,
      projectId?: PromiseOrValue<BigNumberish> | null,
      beneficiary?: PromiseOrValue<string> | null,
      amount?: null,
      note?: null,
      caller?: null
    ): PayEventFilter;
    Pay(
      fundingCycleId?: PromiseOrValue<BigNumberish> | null,
      projectId?: PromiseOrValue<BigNumberish> | null,
      beneficiary?: PromiseOrValue<string> | null,
      amount?: null,
      note?: null,
      caller?: null
    ): PayEventFilter;

    "PrintPreminedTickets(uint256,address,uint256,uint256,string,address)"(
      projectId?: PromiseOrValue<BigNumberish> | null,
      beneficiary?: PromiseOrValue<string> | null,
      amount?: null,
      currency?: null,
      memo?: null,
      caller?: null
    ): PrintPreminedTicketsEventFilter;
    PrintPreminedTickets(
      projectId?: PromiseOrValue<BigNumberish> | null,
      beneficiary?: PromiseOrValue<string> | null,
      amount?: null,
      currency?: null,
      memo?: null,
      caller?: null
    ): PrintPreminedTicketsEventFilter;

    "PrintReserveTickets(uint256,uint256,address,uint256,uint256,address)"(
      fundingCycleId?: PromiseOrValue<BigNumberish> | null,
      projectId?: PromiseOrValue<BigNumberish> | null,
      beneficiary?: PromiseOrValue<string> | null,
      count?: null,
      beneficiaryTicketAmount?: null,
      caller?: null
    ): PrintReserveTicketsEventFilter;
    PrintReserveTickets(
      fundingCycleId?: PromiseOrValue<BigNumberish> | null,
      projectId?: PromiseOrValue<BigNumberish> | null,
      beneficiary?: PromiseOrValue<string> | null,
      count?: null,
      beneficiaryTicketAmount?: null,
      caller?: null
    ): PrintReserveTicketsEventFilter;

    "Redeem(address,address,uint256,uint256,uint256,address)"(
      holder?: PromiseOrValue<string> | null,
      beneficiary?: PromiseOrValue<string> | null,
      _projectId?: PromiseOrValue<BigNumberish> | null,
      amount?: null,
      returnAmount?: null,
      caller?: null
    ): RedeemEventFilter;
    Redeem(
      holder?: PromiseOrValue<string> | null,
      beneficiary?: PromiseOrValue<string> | null,
      _projectId?: PromiseOrValue<BigNumberish> | null,
      amount?: null,
      returnAmount?: null,
      caller?: null
    ): RedeemEventFilter;

    "SetFee(uint256)"(_amount?: null): SetFeeEventFilter;
    SetFee(_amount?: null): SetFeeEventFilter;

    "SetTargetLocalWei(uint256)"(amount?: null): SetTargetLocalWeiEventFilter;
    SetTargetLocalWei(amount?: null): SetTargetLocalWeiEventFilter;

    "SetYielder(address)"(newYielder?: null): SetYielderEventFilter;
    SetYielder(newYielder?: null): SetYielderEventFilter;

    "Tap(uint256,uint256,address,uint256,uint256,uint256,uint256,uint256,address)"(
      fundingCycleId?: PromiseOrValue<BigNumberish> | null,
      projectId?: PromiseOrValue<BigNumberish> | null,
      beneficiary?: PromiseOrValue<string> | null,
      amount?: null,
      currency?: null,
      netTransferAmount?: null,
      beneficiaryTransferAmount?: null,
      govFeeAmount?: null,
      caller?: null
    ): TapEventFilter;
    Tap(
      fundingCycleId?: PromiseOrValue<BigNumberish> | null,
      projectId?: PromiseOrValue<BigNumberish> | null,
      beneficiary?: PromiseOrValue<string> | null,
      amount?: null,
      currency?: null,
      netTransferAmount?: null,
      beneficiaryTransferAmount?: null,
      govFeeAmount?: null,
      caller?: null
    ): TapEventFilter;
  };

  estimateGas: {
    acceptGovernance(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    addToBalance(
      _projectId: PromiseOrValue<BigNumberish>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    allowMigration(
      _contract: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    appointGovernance(
      _pendingGovernance: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    balanceOf(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    canPrintPreminedTickets(
      _projectId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    claimableOverflowOf(
      _account: PromiseOrValue<string>,
      _projectId: PromiseOrValue<BigNumberish>,
      _count: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    configure(
      _projectId: PromiseOrValue<BigNumberish>,
      _properties: FundingCyclePropertiesStruct,
      _metadata: FundingCycleMetadataStruct,
      _payoutMods: PayoutModStruct[],
      _ticketMods: TicketModStruct[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    currentOverflowOf(
      _projectId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    deploy(
      _owner: PromiseOrValue<string>,
      _handle: PromiseOrValue<BytesLike>,
      _uri: PromiseOrValue<string>,
      _properties: FundingCyclePropertiesStruct,
      _metadata: FundingCycleMetadataStruct,
      _payoutMods: PayoutModStruct[],
      _ticketMods: TicketModStruct[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    fee(overrides?: CallOverrides): Promise<BigNumber>;

    fundingCycles(overrides?: CallOverrides): Promise<BigNumber>;

    governance(overrides?: CallOverrides): Promise<BigNumber>;

    migrate(
      _projectId: PromiseOrValue<BigNumberish>,
      _to: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    migrationIsAllowed(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    modStore(overrides?: CallOverrides): Promise<BigNumber>;

    operatorStore(overrides?: CallOverrides): Promise<BigNumber>;

    pay(
      _projectId: PromiseOrValue<BigNumberish>,
      _beneficiary: PromiseOrValue<string>,
      _memo: PromiseOrValue<string>,
      _preferUnstakedTickets: PromiseOrValue<boolean>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    pendingGovernance(overrides?: CallOverrides): Promise<BigNumber>;

    prices(overrides?: CallOverrides): Promise<BigNumber>;

    printPreminedTickets(
      _projectId: PromiseOrValue<BigNumberish>,
      _amount: PromiseOrValue<BigNumberish>,
      _currency: PromiseOrValue<BigNumberish>,
      _beneficiary: PromiseOrValue<string>,
      _memo: PromiseOrValue<string>,
      _preferUnstakedTickets: PromiseOrValue<boolean>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    printReservedTickets(
      _projectId: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    projects(overrides?: CallOverrides): Promise<BigNumber>;

    redeem(
      _account: PromiseOrValue<string>,
      _projectId: PromiseOrValue<BigNumberish>,
      _count: PromiseOrValue<BigNumberish>,
      _minReturnedWei: PromiseOrValue<BigNumberish>,
      _beneficiary: PromiseOrValue<string>,
      _preferUnstaked: PromiseOrValue<boolean>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    reservedTicketBalanceOf(
      _projectId: PromiseOrValue<BigNumberish>,
      _reservedRate: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    setFee(
      _fee: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    tap(
      _projectId: PromiseOrValue<BigNumberish>,
      _amount: PromiseOrValue<BigNumberish>,
      _currency: PromiseOrValue<BigNumberish>,
      _minReturnedWei: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    terminalDirectory(overrides?: CallOverrides): Promise<BigNumber>;

    ticketBooth(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    acceptGovernance(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    addToBalance(
      _projectId: PromiseOrValue<BigNumberish>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    allowMigration(
      _contract: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    appointGovernance(
      _pendingGovernance: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    balanceOf(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    canPrintPreminedTickets(
      _projectId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    claimableOverflowOf(
      _account: PromiseOrValue<string>,
      _projectId: PromiseOrValue<BigNumberish>,
      _count: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    configure(
      _projectId: PromiseOrValue<BigNumberish>,
      _properties: FundingCyclePropertiesStruct,
      _metadata: FundingCycleMetadataStruct,
      _payoutMods: PayoutModStruct[],
      _ticketMods: TicketModStruct[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    currentOverflowOf(
      _projectId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    deploy(
      _owner: PromiseOrValue<string>,
      _handle: PromiseOrValue<BytesLike>,
      _uri: PromiseOrValue<string>,
      _properties: FundingCyclePropertiesStruct,
      _metadata: FundingCycleMetadataStruct,
      _payoutMods: PayoutModStruct[],
      _ticketMods: TicketModStruct[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    fee(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    fundingCycles(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    governance(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    migrate(
      _projectId: PromiseOrValue<BigNumberish>,
      _to: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    migrationIsAllowed(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    modStore(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    operatorStore(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    pay(
      _projectId: PromiseOrValue<BigNumberish>,
      _beneficiary: PromiseOrValue<string>,
      _memo: PromiseOrValue<string>,
      _preferUnstakedTickets: PromiseOrValue<boolean>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    pendingGovernance(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    prices(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    printPreminedTickets(
      _projectId: PromiseOrValue<BigNumberish>,
      _amount: PromiseOrValue<BigNumberish>,
      _currency: PromiseOrValue<BigNumberish>,
      _beneficiary: PromiseOrValue<string>,
      _memo: PromiseOrValue<string>,
      _preferUnstakedTickets: PromiseOrValue<boolean>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    printReservedTickets(
      _projectId: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    projects(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    redeem(
      _account: PromiseOrValue<string>,
      _projectId: PromiseOrValue<BigNumberish>,
      _count: PromiseOrValue<BigNumberish>,
      _minReturnedWei: PromiseOrValue<BigNumberish>,
      _beneficiary: PromiseOrValue<string>,
      _preferUnstaked: PromiseOrValue<boolean>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    reservedTicketBalanceOf(
      _projectId: PromiseOrValue<BigNumberish>,
      _reservedRate: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    setFee(
      _fee: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    tap(
      _projectId: PromiseOrValue<BigNumberish>,
      _amount: PromiseOrValue<BigNumberish>,
      _currency: PromiseOrValue<BigNumberish>,
      _minReturnedWei: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    terminalDirectory(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    ticketBooth(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
