/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ERC721GatedClone } from "./ERC721GatedClone";
export type { ERC721GatedCloner } from "./ERC721GatedCloner";
