/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import { FunctionFragment, Result, EventFragment } from "@ethersproject/abi";
import { Listener, Provider } from "@ethersproject/providers";
import { TypedEventFilter, TypedEvent, TypedListener, OnEvent } from "./common";

export type PayoutModStruct = {
  preferUnstaked: boolean;
  percent: BigNumberish;
  lockedUntil: BigNumberish;
  beneficiary: string;
  allocator: string;
  projectId: BigNumberish;
};

export type PayoutModStructOutput = [
  boolean,
  number,
  number,
  string,
  string,
  BigNumber
] & {
  preferUnstaked: boolean;
  percent: number;
  lockedUntil: number;
  beneficiary: string;
  allocator: string;
  projectId: BigNumber;
};

export type TicketModStruct = {
  preferUnstaked: boolean;
  percent: BigNumberish;
  lockedUntil: BigNumberish;
  beneficiary: string;
};

export type TicketModStructOutput = [boolean, number, number, string] & {
  preferUnstaked: boolean;
  percent: number;
  lockedUntil: number;
  beneficiary: string;
};

export interface IModStoreInterface extends utils.Interface {
  contractName: "IModStore";
  functions: {
    "payoutModsOf(uint256,uint256)": FunctionFragment;
    "projects()": FunctionFragment;
    "setPayoutMods(uint256,uint256,(bool,uint16,uint48,address,address,uint56)[])": FunctionFragment;
    "setTicketMods(uint256,uint256,(bool,uint16,uint48,address)[])": FunctionFragment;
    "ticketModsOf(uint256,uint256)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "payoutModsOf",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "projects", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "setPayoutMods",
    values: [BigNumberish, BigNumberish, PayoutModStruct[]]
  ): string;
  encodeFunctionData(
    functionFragment: "setTicketMods",
    values: [BigNumberish, BigNumberish, TicketModStruct[]]
  ): string;
  encodeFunctionData(
    functionFragment: "ticketModsOf",
    values: [BigNumberish, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "payoutModsOf",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "projects", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setPayoutMods",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setTicketMods",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "ticketModsOf",
    data: BytesLike
  ): Result;

  events: {
    "SetPayoutMod(uint256,uint256,tuple,address)": EventFragment;
    "SetTicketMod(uint256,uint256,tuple,address)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "SetPayoutMod"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "SetTicketMod"): EventFragment;
}

export type SetPayoutModEvent = TypedEvent<
  [BigNumber, BigNumber, PayoutModStructOutput, string],
  {
    projectId: BigNumber;
    configuration: BigNumber;
    mods: PayoutModStructOutput;
    caller: string;
  }
>;

export type SetPayoutModEventFilter = TypedEventFilter<SetPayoutModEvent>;

export type SetTicketModEvent = TypedEvent<
  [BigNumber, BigNumber, TicketModStructOutput, string],
  {
    projectId: BigNumber;
    configuration: BigNumber;
    mods: TicketModStructOutput;
    caller: string;
  }
>;

export type SetTicketModEventFilter = TypedEventFilter<SetTicketModEvent>;

export interface IModStore extends BaseContract {
  contractName: "IModStore";
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: IModStoreInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    payoutModsOf(
      _projectId: BigNumberish,
      _configuration: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[PayoutModStructOutput[]]>;

    projects(overrides?: CallOverrides): Promise<[string]>;

    setPayoutMods(
      _projectId: BigNumberish,
      _configuration: BigNumberish,
      _mods: PayoutModStruct[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setTicketMods(
      _projectId: BigNumberish,
      _configuration: BigNumberish,
      _mods: TicketModStruct[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    ticketModsOf(
      _projectId: BigNumberish,
      _configuration: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[TicketModStructOutput[]]>;
  };

  payoutModsOf(
    _projectId: BigNumberish,
    _configuration: BigNumberish,
    overrides?: CallOverrides
  ): Promise<PayoutModStructOutput[]>;

  projects(overrides?: CallOverrides): Promise<string>;

  setPayoutMods(
    _projectId: BigNumberish,
    _configuration: BigNumberish,
    _mods: PayoutModStruct[],
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setTicketMods(
    _projectId: BigNumberish,
    _configuration: BigNumberish,
    _mods: TicketModStruct[],
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  ticketModsOf(
    _projectId: BigNumberish,
    _configuration: BigNumberish,
    overrides?: CallOverrides
  ): Promise<TicketModStructOutput[]>;

  callStatic: {
    payoutModsOf(
      _projectId: BigNumberish,
      _configuration: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PayoutModStructOutput[]>;

    projects(overrides?: CallOverrides): Promise<string>;

    setPayoutMods(
      _projectId: BigNumberish,
      _configuration: BigNumberish,
      _mods: PayoutModStruct[],
      overrides?: CallOverrides
    ): Promise<void>;

    setTicketMods(
      _projectId: BigNumberish,
      _configuration: BigNumberish,
      _mods: TicketModStruct[],
      overrides?: CallOverrides
    ): Promise<void>;

    ticketModsOf(
      _projectId: BigNumberish,
      _configuration: BigNumberish,
      overrides?: CallOverrides
    ): Promise<TicketModStructOutput[]>;
  };

  filters: {
    "SetPayoutMod(uint256,uint256,tuple,address)"(
      projectId?: BigNumberish | null,
      configuration?: BigNumberish | null,
      mods?: null,
      caller?: null
    ): SetPayoutModEventFilter;
    SetPayoutMod(
      projectId?: BigNumberish | null,
      configuration?: BigNumberish | null,
      mods?: null,
      caller?: null
    ): SetPayoutModEventFilter;

    "SetTicketMod(uint256,uint256,tuple,address)"(
      projectId?: BigNumberish | null,
      configuration?: BigNumberish | null,
      mods?: null,
      caller?: null
    ): SetTicketModEventFilter;
    SetTicketMod(
      projectId?: BigNumberish | null,
      configuration?: BigNumberish | null,
      mods?: null,
      caller?: null
    ): SetTicketModEventFilter;
  };

  estimateGas: {
    payoutModsOf(
      _projectId: BigNumberish,
      _configuration: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    projects(overrides?: CallOverrides): Promise<BigNumber>;

    setPayoutMods(
      _projectId: BigNumberish,
      _configuration: BigNumberish,
      _mods: PayoutModStruct[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setTicketMods(
      _projectId: BigNumberish,
      _configuration: BigNumberish,
      _mods: TicketModStruct[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    ticketModsOf(
      _projectId: BigNumberish,
      _configuration: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    payoutModsOf(
      _projectId: BigNumberish,
      _configuration: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    projects(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    setPayoutMods(
      _projectId: BigNumberish,
      _configuration: BigNumberish,
      _mods: PayoutModStruct[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setTicketMods(
      _projectId: BigNumberish,
      _configuration: BigNumberish,
      _mods: TicketModStruct[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    ticketModsOf(
      _projectId: BigNumberish,
      _configuration: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
